### ISSUE TITLE
alban.andrieu.common was not found on https://galaxy.ansible.com.

### ISSUE THREAD

**Issue by crumgary** [AlbanAndrieu/ansible-jenkins-slave#1]
When running:
ansible-galaxy install alban.andrieu.jenkins-slave

I see:
- downloading role 'jenkins-slave', owned by alban.andrieu
- downloading role from https://github.com/AlbanAndrieu/ansible-jenkins-slave/ar
  chive/master.tar.gz
- extracting alban.andrieu.jenkins-slave to roles/alban.andrieu.jenkins-slave
- alban.andrieu.jenkins-slave was installed successfully
  [DEPRECATION WARNING]: The comma separated role spec format, use the
  yaml/explicit format instead.. This feature will be removed in a future release.
  
  Deprecation warnings can be disabled by setting deprecation_warnings=False in
  ansible.cfg.
- adding dependency: alban.andrieu.common
- adding dependency: geerlingguy.git
- adding dependency: alban.andrieu.cpp
- adding dependency: alban.andrieu.xvbf
- adding dependency: alban.andrieu.selenium
- adding dependency: alban.andrieu.tomcat
- adding dependency: alban.andrieu.jboss
- downloading role 'common', owned by alban.andrieu
  [WARNING]: - alban.andrieu.common was NOT installed successfully: - sorry,
  alban.andrieu.common was not found on https://galaxy.ansible.com. 

I see that the github repo still exists:
https://github.com/AlbanAndrieu/ansible-common

But I don't see it on Ansible Galaxy:
https://galaxy.ansible.com/alban.andrieu/

I'm new to ansible so it could be something with my setup too.

**Comment by eliseshaffer** [comment]
I also have this problem.

**Comment by AlbanAndrieu** [comment]
Indeed, I will try to remove those dependencies.
It will be easier to use this job as standalone without having to much other roles as prerequisite.
This job will be more reusable

**Comment by AlbanAndrieu** [comment]
Does my fix suit you?

**Comment by eliseshaffer** [comment]
@AlbanAndrieu That works for me.

**Comment by AlbanAndrieu** [comment]
Good. I will close the issue then.
Please note that with time. I will remove the maven, java and c++ part from this [role](https://github.com/AlbanAndrieu/ansible-jenkins-slave) and use official roles maintained by the community...

**Comment by gmcquillan** [comment]
Not sure if this change ever got pushed up to ansible galaxy?
