### ISSUE TITLE
Failed to install the role

### ISSUE THREAD

**Issue by lmilbaum** [AlbanAndrieu/ansible-jenkins-slave#2]
ansible-galaxy install alban.andrieu.jenkins-slave -p .
- downloading role 'jenkins-slave', owned by alban.andrieu
- downloading role from https://github.com/AlbanAndrieu/ansible-jenkins-slave/archive/v1.0.0.tar.gz
- extracting alban.andrieu.jenkins-slave to ./alban.andrieu.jenkins-slave
- alban.andrieu.jenkins-slave was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the
yaml/explicit format instead..
This feature will be removed in a future release.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
- adding dependency: alban.andrieu.common
- adding dependency: geerlingguy.git
- adding dependency: alban.andrieu.cpp
- adding dependency: alban.andrieu.xvbf
- adding dependency: alban.andrieu.selenium
- adding dependency: alban.andrieu.tomcat
- adding dependency: alban.andrieu.jboss
- downloading role 'common', owned by alban.andrieu
 [WARNING]: - alban.andrieu.common was NOT installed successfully: - sorry,
alban.andrieu.common was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by fdrueke** [comment]
Try: 
`  ansible-galaxy install albanandrieu.jenkins_slave`
That is how it is described at [ansible galaxy](https://galaxy.ansible.com/albanandrieu/jenkins-slave) .
